import assert from 'node:assert/strict';
import { test } from 'node:test';
import { XiaomiCloudClient } from '../src/cloud/index.js';
import { createNonce, decryptResponse, encryptRequest, rc4, signNonce } from '../src/cloud/crypto.js';

const SECURITY = Buffer.from('0123456789abcdef').toString('base64');
const QR = {
  code: 0,
  qr: 'https://account.xiaomi.com/pass/qr/login?ticket=example',
  loginUrl: 'https://eu.account.xiaomi.com/longPolling/login?ticket=example',
  lp: 'https://eu.lp.account.xiaomi.com/lp/s?k=example',
  timeout: 300,
};
const LOGIN = {
  code: 0, userId: 123456, ssecurity: SECURITY,
  location: 'https://sts.api.io.mi.com/sts?ticket=example',
};
const DEVICE = {
  did: '123', name: 'Living room', model: 'zhimi.airp.rmb1',
  localip: '192.168.1.20', token: '1234567890abcdef1234567890abcdef', isOnline: true,
};
const json = (value: unknown) => new Response(`&&&START&&&${JSON.stringify(value)}`);
const serviceToken = () => new Response('ok', {
  headers: { 'set-cookie': 'serviceToken=test-token; Domain=.sts.api.io.mi.com; Path=/; Secure; HttpOnly' },
});
type Handler = (url: URL, init: RequestInit) => Response | Promise<Response>;
function mocked(...handlers: Handler[]): typeof fetch {
  return (async (input: string | URL | Request, init: RequestInit = {}) => {
    const handler = handlers.shift();
    assert.ok(handler, `Unexpected HTTP request ${new URL(String(input)).pathname}`);
    return handler(new URL(String(input)), init);
  }) as typeof fetch;
}
function encrypted(result: unknown, init: RequestInit): Response {
  const body = init.body as URLSearchParams;
  const nonce = signNonce(SECURITY, body.get('_nonce')!);
  return new Response(rc4(Buffer.from(nonce, 'base64'), Buffer.from(JSON.stringify(result))).toString('base64'));
}
async function authenticate(client: XiaomiCloudClient): Promise<void> {
  await client.startQrLogin();
  assert.equal(await client.pollQrLogin(), 'authenticated');
}

// Published interoperability vector, not generated by this implementation.
// https://www.rfc-editor.org/rfc/rfc6229, section 2, 40-bit key at offset 1024.
test('cloud RC4-drop1024 agrees with the RFC 6229 vector', () => {
  assert.equal(rc4(Buffer.from('0102030405', 'hex'), Buffer.alloc(16)).toString('hex'),
    '30abbcc7c20b01609f23ee2d5f6bb7df');
});

test('nonce includes UTC minutes and encrypted fields are independently recoverable', () => {
  const nonce = createNonce(1_700_000_000_000);
  const bytes = Buffer.from(nonce, 'base64');
  assert.equal(bytes.length, 12);
  assert.equal(bytes.readUInt32BE(8), Math.floor(1_700_000_000_000 / 60_000));
  const result = encryptRequest('/home/device_list', { limit: 200 }, SECURITY, nonce);
  assert.equal(decryptResponse(result.body.get('data')!, result.signedNonce), '{"limit":200}');
  assert.equal(result.body.get('ssecurity'), SECURITY);
  assert.equal(result.body.get('_nonce'), nonce);
  assert.ok(result.body.get('signature'));
  assert.ok(result.body.get('rc4_hash__'));
});

test('QR login supports European account hosts and exchanges its STS cookie', async () => {
  const client = new XiaomiCloudClient({ now: () => 1_000, fetch: mocked(
    (url) => {
      assert.equal(url.searchParams.get('sid'), 'xiaomiio');
      assert.equal(url.searchParams.get('qs'), '%3Fsid%3Dxiaomiio%26_json%3Dtrue');
      return json(QR);
    },
    (url) => { assert.equal(url.hostname, 'eu.lp.account.xiaomi.com'); return json(LOGIN); },
    (url) => { assert.equal(url.hostname, 'sts.api.io.mi.com'); return serviceToken(); },
  ) });
  assert.deepEqual(await client.startQrLogin(), {
    qrImageUrl: QR.qr, loginUrl: QR.loginUrl, expiresAt: 301_000,
  });
  assert.equal(await client.pollQrLogin(), 'authenticated');
  assert.equal(await client.pollQrLogin(), 'authenticated');
  client.reset();
  await assert.rejects(client.getDevices('de'), { code: 'AUTH_REQUIRED' });
});

test('device discovery merges individual shares and paginated homes over encrypted requests', async () => {
  const client = new XiaomiCloudClient({ fetch: mocked(
    () => json(QR), () => json(LOGIN), serviceToken,
    (url, init) => {
      assert.equal(url.href, 'https://de.api.io.mi.com/app/home/device_list');
      const headers = new Headers(init.headers);
      assert.equal(headers.get('MIOT-ENCRYPT-ALGORITHM'), 'ENCRYPT-RC4');
      assert.match(headers.get('Cookie')!, /serviceToken=test-token/);
      assert.equal(init.redirect, 'manual');
      return encrypted({ code: 0, result: { list: [DEVICE] } }, init);
    },
    (url, init) => {
      assert.equal(url.pathname, '/app/v2/homeroom/gethome_merged');
      return encrypted({ code: 0, result: { homelist: [{ id: '5', uid: 123456 }] } }, init);
    },
    (_, init) => encrypted({ code: 0, result: {
      device_info: [{ ...DEVICE, token: 'abcdef1234567890abcdef1234567890' }],
      has_more: true, max_did: '123',
    } }, init),
    (_, init) => {
      const body = init.body as URLSearchParams;
      const payload = JSON.parse(decryptResponse(body.get('data')!, signNonce(SECURITY, body.get('_nonce')!)));
      assert.equal(payload.start_did, '123');
      assert.equal(payload.home_owner, 123456);
      return encrypted({ code: 0, result: { device_info: [{ ...DEVICE, did: '124' }], has_more: false } }, init);
    },
  ) });
  await authenticate(client);
  const devices = await client.getDevices('de');
  assert.equal(devices.length, 2);
  assert.equal(devices[0]?.token, 'abcdef1234567890abcdef1234567890');
  assert.equal(devices[1]?.did, '124');
});

test('API authentication failures discard the session and never echo upstream secrets', async () => {
  const client = new XiaomiCloudClient({ fetch: mocked(
    () => json(QR), () => json(LOGIN), serviceToken,
    (_, init) => encrypted({ code: 3, message: 'secret-account-details' }, init),
  ) });
  await authenticate(client);
  await assert.rejects(client.getDevices('de'), (error: unknown) => {
    assert.ok(error instanceof Error);
    assert.equal((error as Error & { code: string }).code, 'AUTH_EXPIRED');
    assert.doesNotMatch(error.message, /secret-account-details/);
    return true;
  });
  await assert.rejects(client.getDevices('de'), { code: 'AUTH_REQUIRED' });
});

test('QR expiry and pending status require no credentials and no background timer', async () => {
  let now = 1_000;
  const client = new XiaomiCloudClient({ now: () => now, fetch: mocked(
    () => json(QR), () => new Response(null, { status: 204 }),
  ) });
  await client.startQrLogin();
  assert.equal(await client.pollQrLogin(), 'pending');
  now = 301_000;
  assert.equal(await client.pollQrLogin(), 'expired');
  await assert.rejects(client.pollQrLogin(), { code: 'AUTH_REQUIRED' });
});

test('external QR addresses and hostile redirects are rejected before credentials can leave Xiaomi', async () => {
  const first = new XiaomiCloudClient({ fetch: mocked(
    () => json({ ...QR, qr: 'https://account.xiaomi.com.evil.example/login' }),
  ) });
  await assert.rejects(first.startQrLogin(), { code: 'UNSAFE_URL' });
  const second = new XiaomiCloudClient({ fetch: mocked(
    () => new Response(null, { status: 302, headers: { location: 'http://127.0.0.1/private' } }),
  ) });
  await assert.rejects(second.startQrLogin(), { code: 'UNSAFE_URL' });
});

test('QR verification challenges do not expose sensitive provider URLs', async () => {
  const client = new XiaomiCloudClient({ fetch: mocked(
    () => json(QR), () => json({ code: 0, notificationUrl: 'https://account.xiaomi.com/secret-challenge' }),
  ) });
  await client.startQrLogin();
  await assert.rejects(client.pollQrLogin(), (error: unknown) => {
    assert.ok(error instanceof Error);
    assert.match(error.message, /verification/);
    assert.doesNotMatch(error.message, /secret-challenge/);
    return true;
  });
  await assert.rejects(client.pollQrLogin(), { code: 'AUTH_REQUIRED' });
});

test('logout cancels an in-flight poll and cannot resurrect the session', async () => {
  let release!: (response: Response) => void;
  let entered!: () => void;
  const started = new Promise<void>(resolve => { entered = resolve; });
  const client = new XiaomiCloudClient({ fetch: mocked(
    () => json(QR),
    (_, init) => {
      entered();
      assert.ok(init.signal);
      return new Promise(resolve => { release = resolve; });
    },
  ) });
  await client.startQrLogin();
  const pending = client.pollQrLogin();
  await started;
  await assert.rejects(client.pollQrLogin(), { code: 'BUSY' });
  client.reset();
  release(json(LOGIN));
  await assert.rejects(pending, { code: 'AUTH_EXPIRED' });
  await assert.rejects(client.getDevices('de'), { code: 'AUTH_REQUIRED' });
});

test('cookie jar respects host and path and retains service cookies across redirects', async () => {
  const client = new XiaomiCloudClient({ fetch: mocked(
    () => new Response(JSON.stringify(QR), { headers: {
      'set-cookie': 'privateAccountCookie=secret; Path=/identity; Secure',
    } }),
    (_, init) => {
      assert.doesNotMatch(new Headers(init.headers).get('Cookie')!, /privateAccountCookie/);
      return json(LOGIN);
    },
    (_, init) => {
      assert.doesNotMatch(new Headers(init.headers).get('Cookie')!, /privateAccountCookie/);
      return new Response(null, { status: 302, headers: {
        location: '/complete', 'set-cookie': 'serviceToken=test-token; Domain=.sts.api.io.mi.com; Path=/; Secure',
      } });
    },
    (_, init) => {
      assert.match(new Headers(init.headers).get('Cookie')!, /serviceToken=test-token/);
      return new Response('ok');
    },
  ) });
  await authenticate(client);
});

test('malformed pagination fails explicitly instead of dropping later devices', async () => {
  const client = new XiaomiCloudClient({ fetch: mocked(
    () => json(QR), () => json(LOGIN), serviceToken,
    () => json({ code: 0, result: { list: [] } }),
    () => json({ code: 0, result: { homelist: [{ id: '1', uid: 123456 }] } }),
    () => json({ code: 0, result: { device_info: [DEVICE], has_more: true } }),
  ) });
  await authenticate(client);
  await assert.rejects(client.getDevices('de'), { code: 'INVALID_RESPONSE' });
});

for (const domain of ['.io.mi.com', '.mi.com']) {
  test(`STS accepts a valid service token scoped to parent domain ${domain}`, async () => {
    const client = new XiaomiCloudClient({ fetch: mocked(
      () => json(QR), () => json(LOGIN),
      () => new Response('ok', { headers: {
        'set-cookie': `serviceToken=parent-scope-token; Domain=${domain}; Path=/; Secure`,
      } }),
      (_, init) => {
        assert.match(new Headers(init.headers).get('Cookie')!, /serviceToken=parent-scope-token/);
        return encrypted({ code: 0, result: { list: [] } }, init);
      },
      (_, init) => encrypted({ code: 0, result: { homelist: [] } }, init),
    ) });
    await authenticate(client);
    assert.deepEqual(await client.getDevices('de'), []);
  });
}
